-- TODA TABELA TEM UMA CHAVE PRIMÁRIA
-- MODELO RELACIONAL (TABELAS QUE SE RELACIONAM)
-- TODO COMANDO SQL É EM INGLÊS
-- TODO COMANDO TERMINA COM ;
-- CRIAR O BANCO DE DADOS (SCHEMA OU DATABASE)
CREATE DATABASE sptecha;

-- UTILIZAR O BANCO DE DADOS
USE sptecha;

-- CRIAR A NOSSA PRIMEIRA TABELA
CREATE TABLE aluno (
-- nomeCampo tipagem restrição/constraint
ra char(8) primary key,
nome varchar(100),
bairro varchar(50)
);

-- VERIFICAR A ESTRUTURA DA TABELA
DESCRIBE aluno;
DESC aluno;

-- EXIBIR OS DADOS DA TABELA
SELECT ra, nome, bairro FROM aluno;
SELECT * FROM aluno;

-- INSERIR DADOS NA TABELA
INSERT INTO aluno VALUES 
	('01231062', 'GABRIELLI', 'JARDIM PERI');
    
-- INSERIR VÁRIOS ALUNOS NO MESMO COMANDO
INSERT INTO aluno VALUES
	('01231058', 'HENRIQUE', 'PAULICEIA'),
    ('01231059', 'ZAPATTA', 'VILA FLORIDA'),
    ('01231003', 'WILL', 'GUAIANASES'),
    ('01231169', 'GUSTAVO', 'ITAQUÁ');
    
-- EXIBIR O ALUNO COM O NOME GABRIELLI
SELECT * FROM aluno WHERE nome = 'GABRIELLI';

-- ATUALIZAR O BAIRRO DA GABRIELLI
UPDATE aluno SET bairro = 'PAULISTA' WHERE ra = '01231062';

UPDATE aluno SET bairro = 'Butanta', nome = 'João' 
	WHERE ra = '01231062';

-- BONS ESTUDOS!

-- AULA 2 - 16/02
-- CREATE DATABASE sptecha;
USE sptecha;

-- EXCLUIR UMA TABELA INTEIRA
DROP TABLE aluno;

-- ctrl enter nas linhas 12, 28, 32
SELECT * FROM aluno;

-- ADICIONAR UM CAMPO NA TABELA ALUNO
ALTER TABLE aluno ADD COLUMN email VARCHAR(100) NOT NULL;
DESC aluno;

SELECT * FROM aluno;

-- ATUALIZAR OS EMAILS DOS ALUNOS
UPDATE aluno SET email = 'will@sptech.school'
	WHERE ra = '01231003';
    
UPDATE aluno SET email = 'henrique@sptech.school'
	WHERE ra = '01231058';
    
UPDATE aluno SET email = 'zapatta@sptech.school'
	WHERE ra = '01231059';
    
UPDATE aluno SET email = 'gabrielli@sptech.school'
	WHERE ra = '01231062';
    
UPDATE aluno SET email = 'gustavo@sptech.school'
	WHERE ra = '01231169';
    
-- ADICIONAR A COLUNA DATA DE NASCIMENTO
ALTER TABLE aluno ADD COLUMN dtNasc DATE;
DESC aluno;

-- tipagem do tipo data (DATE - 'AAAA-MM-DD')
SELECT * FROM aluno;
UPDATE aluno SET dtNasc = '2002-03-29'
	WHERE ra = '01231059';
    
-- RENOMEAR O CAMPO DataNasc
ALTER TABLE aluno RENAME COLUMN dtNasc TO dataNasc;
DESC aluno;
    
-- EXCLUIR O CAMPO DATANASC
ALTER TABLE aluno DROP COLUMN dataNasc;

-- MODIFICAR O CAMPO EMAIL PARA VARCHAR(120)
ALTER TABLE aluno MODIFY COLUMN email VARCHAR(120) NOT NULL;

-- OS CAMPOS RA E EMAIL SÃO OBRIGATÓRIOS
-- BORA INSERIR APENAS ESSES CAMPOS
INSERT INTO aluno (ra, email) VALUES
	('01231999', 'vivian@sptech.school');
SELECT * FROM aluno;

-- EXCLUIR A TUPLA/REGISTRO/LINHA DA PROF VIVIAN
DELETE FROM aluno WHERE ra = '01231999';

-- SELECTS MAROTOS
-- EXIBIR O NOME WILL
SELECT nome FROM aluno WHERE nome = 'WILL';

-- EXIBIR OS DADOS DOS ALUNOS CUJO NOME COMEÇA COM A LETRA G
SELECT * FROM aluno WHERE nome LIKE 'G%';

-- EXIBIR OS DADOS DOS ALUNOS CUJO NOME CONTEM A LETRA I
SELECT * FROM aluno WHERE nome LIKE '%I%';

-- EXIBIR OS DADOS DOS ALUNOS CUJO RA TERMINA COM O NUM 9
SELECT * FROM aluno WHERE ra LIKE '%9';

-- EXIBIR OS DADOS DOS ALUNOS CUJO BAIRRO POSSUI ESPAÇO E A 
-- PRIMEIRA LETRA APÓS ESPAÇO É P
SELECT * FROM aluno WHERE bairro LIKE '% P%';

SELECT * FROM aluno;
-- EXIBIR OS DADOS ALUNOS ONDE O BAIRRO TEM COMO SEGUNDA LETRA A
SELECT * FROM aluno WHERE bairro LIKE '_A%';

-- EXIBIR OS DADOS DOS ALUNOS ONDE O BAIRRO TEM COMO PENULTIMA LETRA R
SELECT * FROM aluno WHERE bairro LIKE '%R_';

-- EXIBIR OS DADOS DOS ALUNOS ORDENADOS PELO NOME
SELECT * FROM aluno ORDER BY nome;

-- EXIBIR OS DADOS DOS ALUNOS ORDENADOS PELO NOME EM ORDEM DECRESCENTE
SELECT * FROM aluno ORDER BY nome DESC;
SELECT * FROM aluno ORDER BY ra DESC;

-- JUNTANDO 2 SELECTS
SELECT * FROM aluno WHERE nome LIKE 'G%' ORDER BY bairro;
SELECT * FROM aluno WHERE nome LIKE 'G%' OR nome LIKE '%A';
SELECT * FROM aluno WHERE nome LIKE 'G%' AND bairro LIKE 'J%';

-- CRIAR A TABELA EMPRESA
CREATE TABLE empresa (
id INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(100),
responsavel VARCHAR(50)
);

INSERT INTO empresa (nome, responsavel) VALUES
	('C6', 'Andresa'),
    ('Stefanini', 'Sophia'),
    ('Box Delivery', 'Erika');
    
SELECT * FROM empresa;

-- LIMPAR OS REGISTROS DA TABELA
TRUNCATE TABLE empresa;

-- BONS ESTUDOS!