-- TODA TABELA TEM UMA CHAVE PRIMÁRIA
-- MODELO RELACIONAL (TABELAS QUE SE RELACIONAM)
-- TODO COMANDO SQL É EM INGLÊS
-- TODO COMANDO TERMINA COM ;
-- CRIAR O BANCO DE DADOS (SCHEMA OU DATABASE)
CREATE DATABASE sptecha;

-- UTILIZAR O BANCO DE DADOS
USE sptecha;

-- CRIAR A NOSSA PRIMEIRA TABELA
CREATE TABLE aluno (
-- nomeCampo tipagem restrição/constraint
ra char(8) primary key,
nome varchar(100),
bairro varchar(50)
);

-- VERIFICAR A ESTRUTURA DA TABELA
DESCRIBE aluno;
DESC aluno;

-- EXIBIR OS DADOS DA TABELA
SELECT ra, nome, bairro FROM aluno;
SELECT * FROM aluno;

-- INSERIR DADOS NA TABELA
INSERT INTO aluno VALUES 
	('01231062', 'GABRIELLI', 'JARDIM PERI');
    
-- INSERIR VÁRIOS ALUNOS NO MESMO COMANDO
INSERT INTO aluno VALUES
	('01231058', 'HENRIQUE', 'PAULICEIA'),
    ('01231059', 'ZAPATTA', 'VILA FLORIDA'),
    ('01231003', 'WILL', 'GUAIANASES'),
    ('01231169', 'GUSTAVO', 'ITAQUÁ');
    
-- EXIBIR O ALUNO COM O NOME GABRIELLI
SELECT * FROM aluno WHERE nome = 'GABRIELLI';

-- ATUALIZAR O BAIRRO DA GABRIELLI
UPDATE aluno SET bairro = 'PAULISTA' WHERE ra = '01231062';

UPDATE aluno SET bairro = 'Butanta', nome = 'João' 
	WHERE ra = '01231062';

-- BONS ESTUDOS!